default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: micro_post_development

test:
  <<: *default
  database: micro_post_test

production:
  <<: *default
  database: micro_post_production
  username: little_owl
  password: <%= ENV['MICRO_POST_DATABASE_PASSWORD'] %>
